### ISSUE TITLE
Move TSM calculation tests to the `pytest` directory -> get them passing

### ISSUE THREAD

**Issue by xaviernogueira** [EcohydrologyTeam/ClearWater-modules#20]
This can be closed once we are confident in the calculations being done by the refactored TSM model.
The testing code may need to be updated to work with the refactored pattern.

**Tasks:**

- [x] Right now `xarray.apply_ufunc` is not working with Reynold Number calculation (which contains if/else). This needs to be resolved before this issue can be solved. -> solved w/ #39 
- [x] Double check that the `TSM Manual Checks_1D timestep.xlsx` constant / input values match our defaults. Even if they do, since defaults might change, we should hard code this into the test suite.
- [ ] Create a test for every case in the XLSX file, instantiate a fresh model and run each time.
- [ ] Assess if there are calculation issues, if so, try to diagnose them.

**Comment by xaviernogueira** [comment]
@imscw95 So I ran the  first test (nothing changed, just defaults as shown in your Excel) and I am getting a different answer. I want to check in with you to better understand how the calculations differ. Let me know your availability either in the next two hours, or early next week?

**Comment by imscw95** [comment]
Hey Xavier. I can meet on Monday. I am on the road right now. How's 9-10ET?

**Comment by xaviernogueira** [comment]
Works for me, i'll shoot you an invite

**Comment by xaviernogueira** [comment]
**Updates:**

* We want to have an xarray with a "test" dimension with different initial conditions, then we run a timestep for each, and check the answers.
* We want to check answers for all the "fluxes".
* The test dimension is analogous to the spatial dimension, therefore you can just calculate it all in one step.
